target_panel: {
  State: {
    "segment_stage": "control_debug:segment_stage",
    # "apa_state": "control_debug:mc_apa_state",
  },
  # SegmentID: {
  #   "segment_id": "control_debug:segment_id",
  # },
  TailDistance: {
    "distance_to_entrance_line": "control_debug:front_heading_error",
    "increase_torque_position_": "control_debug:hpp_target_steer_bkp_deg",
    "brake_position_": "control_debug:hpp_target_steer_deg",
  },
  StopDistance: {
    # "stop_distance_req": "control_cmd:stop_distance_req",
    "end_y_error": "control_debug:end_y_error",
    "stop_distance": "control_debug:target_steer_deg",
    "stop_distance1": "control_debug:previous_target_steer_deg",
    # "front_y_error": "control_debug:front_y_error",
    # "distance_threshold_0_": "control_debug:reference_station_error_m",
    # "distance_threshold_1_": "control_debug:start_steer",
    # "distance_threshold_2_": "control_debug:heading_compensation_steer_value",
  },
  ramp_slope: {
    "slope_degree_used": "control_debug:start_steer",
    "slope_degree_": "control_debug:previous_target_acc_mpss",
    # "stop_distance": "control_debug:target_steer_deg",
    # "stop_distance1": "control_debug:previous_target_steer_deg",
  },
  jerk: {
    "jerk": "control_debug:max_speed_mps_req",
    "torque_gain_": "control_debug:target_acc_mpss",
  },
  pitch: {
    # "vehicle_pitch": "dr:pitch",
    "vehicle_pitch": "control_debug:stop_dist_cm_req",
    
  },
  height_rate: {
    "pitch_rate": "control_debug:heading_compensation_steer_value",
  },
  InSlope: {
    "need_increase_torque_": "control_debug:goal_complete_flag",
    "need_brake_": "control_debug:segment_finished",
    # "pitch_in_stereo_slot_counter_": "control_debug:delay_acc_count",
  },
  Speed: {
    # "vehicle_speed": "chassis:vehicle_speed",
    "vehicle_speed": "control_debug:target_acc_mpss",
    # "speed_error": "control_debug:speed_error",
    "planned_speed": "control_debug:planned_speed",
  },
  Acc: {
    "imu_acc_": "control_debug:imu_acc_",
    # "acc_filtered": "control_debug:acc_filtered",
    "original_target_acc_mpss": "control_debug:origin_control_acc_mpss",
    "target_acc_mpss": "control_cmd:target_acc_mpss",
    # "acc_cmd_closeloop":"control_debug:acc_cmd_closeloop",
    # "feedforward_acc":"control_debug:previous_acceleration_reference",
    # "feedback_acc":"control_debug:slope_acc",
    # "p_error":"control_debug:p_error",
    # "i_error":"control_debug:i_error",
  },
  Torque: {
    "front_motor_torque_nm": "chassis:front_motor_torque_nm",
    "front_motor_torque_req_nm": "chassis:front_motor_torque_req_nm",
    "rear_motor_torque_nm": "chassis:rear_motor_torque_nm",
    "rear_motor_torque_req_nm": "chassis:rear_motor_torque_req_nm",
  },
  Brake: {
    "master_pressure": "chassis:master_pressure",
  },
  Collision: {
    "collision_type": "hmi_report:collision_type_int",
    "preview_environment_status": "control_debug:previous_ref_heading_acceleration",
    "current_environment_status": "control_debug:previous_lateral_error_acceleration",
  },
  Heading_Error: {
    # "reference_heading_rad": "control_debug:reference_heading_rad",
    # "preview_reference_heading_rad": "control_debug:preview_reference_heading_rad",
    # "preview_yaw_error": "control_debug:lookahead_station_low_speed",
    "heading_error": "control_debug:heading_error_feedback",
  },
  Lat_Error: {
    "lat_error": "control_debug:lateral_error",
    # "lat_error2": "control_debug:end_x_error",
  },
  APAState: {
    "apa_state": "control_debug:mc_apa_state",
  },
  Gear: {
    "gear_position": "chassis:gear_position",
    # "target_gear": "control_cmd:target_gear",
  },
  # Heading_Error: {
  #   "reference_heading_rad": "control_debug:reference_heading_rad",
  #   "preview_reference_heading_rad": "control_debug:preview_reference_heading_rad",
  #   "preview_yaw_error": "control_debug:lookahead_station_low_speed",
  #   "heading_error": "control_debug:heading_error_feedback",
  # },
  # Lat_Error: {
  #   "lat_error": "control_debug:lateral_error",
  #   "lat_error2": "control_debug:end_x_error",
  # },
  LatCmd: {
    "feedward_kappa": "control_debug:feedward_kappa",
    "preview_kappa": "control_debug:preview_kappa",
    "preview_kappa_c": "control_debug:preview_kappa_c",
    "origin_control_kappa": "control_debug:origin_control_kappa",
    "origin_control_steer_deg": "control_debug:origin_control_steer_deg",
    "reference_kappa": "control_debug:reference_kappa",
    "reference_kappa_c": "control_debug:reference_kappa_c",
  },
  Steer: {
    "steer_wheel_angle": "chassis:steer_wheel_angle",
    "steer_wheel_angle_deg_bkp": "chassis:steer_wheel_angle_deg_bkp",
    "target_steer_deg": "control_cmd:target_steer_deg",
  },
  Lat: {
    "stanley_lateral_contribution": "control_debug:stanley_lateral_contribution",
  },
  Heading: {
    "stanley_yaw_contribution": "control_debug:stanley_yaw_contribution",
  },
}