target_panel: {
  State: {
    # controller state
    "apa_status": "apa_statemachine:status",
    "apa_active_sub_status": "apa_statemachine:active_sub_function_status",
    "hpp_status": "apa_statemachine:hpp_status",
    "hpp_active_sub_status": "apa_statemachine:hpp_active_sub_status",
    "quit_reason": "apa_statemachine:quit_reason_description",
    "parking_brake_status": "apa_statemachine:parking_brake_status",
    "working_status": "parking_controller_to_state_machine:controller_working_status",
    "mc_apa_status": "control_debug:mc_apa_state",
    "segment_stage": "control_debug:segment_stage",
    "original_segment_stage": "control_debug:delay_acc_count",
    "segment_finished": "control_debug:segment_finished",

    # torque controller state
    "torque_controller_status": "control_debug:torque_controller_status",
    "drive_off": "control_cmd:drive_off_req",
    "drive_off_req": "control_debug:drive_off_req",
    "standstill": "control_cmd:standstill_req",
    "keep_standstill": "control_debug:keep_standstill",
    "is_creep": "control_debug:is_creep",
    "release_bcs_flag": "control_debug:release_bcs_flag",

    # slipping state
    "is_sliping": "control_debug:is_sliping",
    "is_sliping_static": "control_debug:is_sliping_static",
    "sliping_counter": "control_debug:sliping_counter",
    "slip_static_counter": "control_debug:slip_static_counter",

    # stuck state
    "should_running": "control_debug:should_running",
    # "meet_crossing_condition": "control_debug:meet_crossing_condition",
    "stuck_counter": "control_debug:stuck_counter",
    "stuck_state": "control_debug:stuck_state",
    "is_crossing_over": "control_debug:is_crossing_over",


    # stereo state
    "is_target_slot_stereo": "control_debug:is_target_slot_stereo",
    "stereo_lot_flag": "control_debug:stereo_lot_flag",
    "stereo_stage": "control_debug:stereo_stage",
    "is_in_stereo_slope": "control_debug:is_in_stereo_slope",
    "exit_slope_flag": "control_debug:exit_slope_flag",
    "enter_slope_flag": "control_debug:enter_slope_flag",
    "pitch_in_stereo_slot_counter": "control_debug:pitch_in_stereo_slot_counter",
    "pitch_in_stereo_slot_exit_counter": "control_debug:pitch_in_stereo_slot_exit_counter",
    "need_brake": "control_debug:stereo_slot_need_brake",
    "pitch_gain": "control_debug:pitch_gain",

    # abnormal state
    "is_abnormal": "control_debug:is_abnormal",
    "is_switching_gear_without_stopping": "control_debug:is_switching_gear_without_stopping",
    "is_stuck": "control_debug:is_stuck",
    "is_short_stuck": "control_debug:is_short_stuck",
    "is_running_apa": "control_debug:stereo_slot_need_increase_torque",
    "startup_stuck": "control_debug:is_short_stuck",
    "is_large_torque_for_stopping": "control_debug:meet_crossing_condition",
    "too_large_torque_": "control_debug:goal_complete_flag",
    "segment_gear": "control_debug:segment_gear",
    
    # vehicle state
    "brake_pedal_status": "chassis:brake_pedal_status",
    "epb_reqest_torque": "control_cmd:epb_request",
    "epb_reqest_acc": "control_cmd:epb_req",
    "epb_status": "chassis:epb_status",
    "extrmirr_req_flag": "parking_controller_to_state_machine:extrmirr_req_flag",
    "avh_cmd": "control_cmd:avh_req",
    "avh_status": "chassis:avh_status",
    "avh_cmd_debug": "control_debug:epb_req",
    "last_traj": "parking_controller_to_state_machine:last_traj_out_slot",
    "request_cruising": "parking_controller_to_state_machine:apa_control_mode_request_cruising",
    
    "planning_success_status": "apa_planner_status:apa_trajectory_planning_success_status",
  },
  # StuckCounter: {
  #   "stuck_counter": "control_debug:delay_acc_count",
  # },  
  StopDistance: {
    # "stop_distance_req": "control_cmd:stop_distance_req",
    "end_y_error": "control_debug:end_y_error",
    "distance_to_front_wheel_exit_slope_position": "control_debug:distance_to_front_wheel_exit_slope_position",
    # "rear_y_error": "control_debug:rear_y_error",
    "stop_distance_req": "control_debug:stereo_slot_stop_distance",
    "brake_distance_est": "control_debug:stereo_slot_increase_torque_position",
  }, 
  Speed: {
    # "chassis_speed": "chassis:vehicle_speed",
    "vehicle_speed": "control_debug:vehiclestate_linear_velocity",
    # "estimated_speed": "control_debug:speed_estimated",
    # "speed_error": "control_debug:speed_error",
    "planned_speed": "control_debug:planned_speed",
    "rear_wheel_start_climbing_v_": "control_debug:stereo_slot_slope_degree",
    "rear_wheel_finish_climbing_v_": "control_debug:slope_degree",
  },
  Torque: {
    "target_torque_vcu": "control_cmd:target_torque_vcu",
    "target_torque_bcs": "control_cmd:target_torque_bcs",
    "raw_torque_for_standstill": "control_debug:raw_torque_for_standstill",
    "target_torque": "control_debug:target_torque",
    "torque_feedforward": "control_debug:torque_feedforward",
    "torque_feedback": "control_debug:torque_feedback",
    "proportional_term": "control_debug:torque_control_proportional_term",
    "integral_term": "control_debug:torque_control_integral_term",
    "derivative_term": "control_debug:torque_control_derivative_term",
    "aero_drag_nm": "control_debug:aero_drag_nm",
    "rolling_resistance_nm": "control_debug:rolling_resistance_nm",
    "slope_resistance_nm": "control_debug:slope_resistance_nm",
    "acc_resistance_nm": "control_debug:acc_resistance_nm",
    "front_motor_torque_nm": "chassis:front_motor_torque_nm",
    "front_motor_torque_req_nm": "chassis:front_motor_torque_req_nm",
    "rear_motor_torque_nm": "chassis:rear_motor_torque_nm",
    "rear_motor_torque_req_nm": "chassis:rear_motor_torque_req_nm",
    "bcs_torque": "chassis:bcs_torque",
    "bcs_torque_user": "chassis:bcs_torque_requested_by_pedal",
  },
  Acc: {
    "imu_acc_": "control_debug:imu_acc_",
    "target_acc_mpss": "control_cmd:target_acc_mpss",
    "acc_prediction": "control_debug:stuck_position",
    "origin_control_acc_mpss":"control_debug:origin_control_acc_mpss",
    "planned_acc": "control_debug:planned_acc",
    "acc_estimated": "control_debug:acc_estimated",
    "pid_cmd":"control_debug:acc_cmd_closeloop",
    "feedforward_acc":"control_debug:previous_acceleration_reference",
    "feedback_acc":"control_debug:slope_acc",
    "p_error":"control_debug:p_error",
    "i_error":"control_debug:i_error",
  },
  pitch: {
    # "vehicle_pitch": "dr:pitch",
    "vehicle_pitch": "control_debug:vehicle_pitch",
  },
  Gear: {
    "gear_position": "chassis:gear_position",
    "target_gear": "control_cmd:target_gear",
  }, 
  Jerk: {
    "jerk_deceleration_stop_origin_": "control_debug:previous_target_acc_mpss",
    "jerk_deceleration_stop_": "control_debug:max_speed_mps_req",
  },
  Brake: {
    "master_pressure": "chassis:master_pressure",
  },
  TorqueGradient: {
    "target_gradient_vcu": "control_debug:target_gradient_vcu",
    "target_gradient_bcs": "control_debug:target_gradient_bcs",
  },
  # Gear: {
  #   "gear_position": "chassis:gear_position",
  #   "target_gear": "control_cmd:target_gear",
  # }, 
  TailDistance: {
    "distance_to_entrance_line": "control_debug:front_heading_error",
    # "rear_exit_slope_position_": "control_debug:stereo_slot_brake_position",
    "front_enter_slope_position_": "control_debug:front_wheel_enter_slope_position",
    "front_exit_slope_position_": "control_debug:front_wheel_exit_slope_position",
    "rear_enter_slope_position_": "control_debug:enter_slope_position",
    "rear_exit_slope_position_": "control_debug:exit_slope_position",
  },
  Collision: {
    "collision_type": "hmi_report:collision_type_int",
    "preview_environment_status": "control_debug:previous_ref_heading_acceleration",
    "current_environment_status": "control_debug:previous_lateral_error_acceleration",
  }, 
  # Energy: {
  #   "rear_wheel_climbing_drive_energy_": "control_debug:vehicle_jerk",
  #   "resistance_energy_": "control_debug:previous_target_acc_mpss",
  # },
  ramp_slope: {
    "slope_degree_used": "control_debug:stereo_slot_slope_degree",
    "slope_degree_": "control_debug:slope_degree",
    # "stop_distance": "control_debug:target_steer_deg",
    # "stop_distance1": "control_debug:previous_target_steer_deg",
  },
  APAState: {
    "apa_state": "control_debug:mc_apa_state",
  },
  LatCmd: {
    "feedward_kappa": "control_debug:feedward_kappa",
    "preview_kappa": "control_debug:preview_kappa",
    "origin_control_kappa": "control_debug:origin_control_kappa",
    "reference_kappa": "control_debug:reference_kappa",
  },
  Lat: {
    "stanley_lateral_contribution": "control_debug:stanley_lateral_contribution",
  },
  Heading: {
    "stanley_yaw_contribution": "control_debug:stanley_yaw_contribution",    
    "reference_heading_rad": "control_debug:reference_heading_rad",
    "preview_reference_heading_rad": "control_debug:preview_reference_heading_rad",
    "vehicle_state_heading": "control_debug:vehiclestate_heading",
    # "dr_heading": "dr:heading",
  },
  Heading_Error: {

    "preview_yaw_error": "control_debug:lookahead_station_low_speed",
    "rear_heading_error_used": "control_debug:heading_error_feedback",
    "rear_heading_error_measured": "control_debug:rear_heading_error",
    "end_heading_error": "control_debug:end_heading_error",
  },
  Lat_Error: {
    "rear_x_error": "control_debug:lateral_error",
    "end_x_error": "control_debug:end_x_error",
  },
  Steer: {
    "preview_steer": "control_debug:preview_kappa_c",
    "origin_control_steer": "control_debug:origin_control_steer_deg",
    "reference_steer": "control_debug:reference_kappa_c",
    "steer_wheel_angle": "chassis:steer_wheel_angle",
    "steer_wheel_angle_deg_bkp": "chassis:steer_wheel_angle_deg_bkp",
    "target_steer_deg": "control_cmd:target_steer_deg",
  },
}