#!/bin/bash
RunPNCPerformanceAnalyzer(){
    python ${pnc_analyzer_dir}/pnc_performance_analyzer.py \
        --bag $1 \
        --test-file $2 \
        --vehicle-name ${vehicle_name} \
        --output-dir ${simulation_output_dir}/evaluation\
        --log-dir ${simulation_output_dir}/logs\
        --not-snip-bag \
        --is-simulation \
        --fuel-param ${pnc_analyzer_dir}/example/fuel_param_sim.yaml
}

CopyOutput(){
    bag_name=$1
    bag_name_without_postfix=${bag_name%.*}
    
	target_dir=${pwd}/report/simulation_report
	
	target_report_filepath=${target_dir}/${time}/${bag_name_without_postfix}
	if [ ! -d ${target_report_filepath} ]; then
		mkdir -p ${target_report_filepath}
	fi
	cp -r ${simulation_output_dir} ${target_report_filepath}

    echo "==============finish ${bag_name_without_postfix}==================="
}

# bag_type = sim: analyze the bag generated by simulator
# bag_type = bagdb: analyze the bag of roadtest
bag_type=$1
pwd=$(pwd -P)
lwd=$(dirname $pwd)
time=$(date "+%Y%m%d%H%M%S")
vehicle_name=j7-l4e-sim
export drive_root=../drive/opt/relwithdebinfo
rm -rf ${simulation_output_dir}/evaluation/*
simulation_output_dir=${lwd}/simulator/scenario/simulation_output
pnc_analyzer_dir=${lwd}/simulator/scenario/tools/pnc_performance_analyzer
benchmark_dir=${lwd}/simulator/scenario/scenario_test/benchmark/CN/L4E

bagdb_dir=${pwd}/report/simulation_report/20221222214824/benchmark_fe_20221205T095000_j7-l4e-LFWSRXSJ7M1F48985_2_1001to1041/simulation_output/bag
test_file=${benchmark_dir}/fe/benchmark_fe_20221205T095000_j7-l4e-LFWSRXSJ7M1F48985_2_1001to1041.prototxt

bagdb_dir=${pwd}/report/simulation_report/20221222221808/benchmark_fe_20221117T134511_j7-l4e-LFWSRXSJ7M1F48985_4/simulation_output/bag/
test_file=${benchmark_dir}/fe/benchmark_fe_20221205T095000_j7-l4e-LFWSRXSJ7M1F48985_2.prototxt

# bagdb_dir=${pwd}/report/simulation_report/20221222221808/benchmark_fe_20221117T134511_j7-l4e-LFWSRXSJ7M1F48985_4/simulation_output/bag
# test_file=${benchmark_dir}/fe/benchmark_fe_20221117T134511_j7-l4e-LFWSRXSJ7M1F48985_4.prototxt

if [ ${bag_type} == 'sim' ];then
    target_bag_path=${simulation_output_dir}/bag
    for file in $(ls ${target_bag_path})
    do 
        target_bag_file=${target_bag_path}/${file}
        RunPNCPerformanceAnalyzer ${target_bag_file} ${test_file}
        target_folder=${lwd}/scripts/simulation_report/pnc_analysis_report
        CopyOutput ${file} ${target_folder}
    done
elif [ ${bag_type} == 'bagdb' ];then
    target_bag_path=${bagdb_dir}
    for file in $(ls ${target_bag_path})
    do 
        target_bag_file=${target_bag_path}/${file}
        RunPNCPerformanceAnalyzer ${target_bag_file} ${test_file}
        target_folder=${lwd}/scripts/bag_report/pnc_analysis_report
        CopyOutput ${file} ${target_folder}
    done
else
    echo "[ERROR]: bag type should be 'sim' or 'bagdb'"
fi